- name: Install Python
  ansible.builtin.import_role:
    name: common
    tasks_from: python-setup
  
- name: Setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: download dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Start application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup