- name: Configure rabbitmq yum repos
  ansible.builtin.shell: "{{item}}"
  loop:
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
  
- name: Install RabbitMQ server
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: start and enable rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Create RabbitMQ user & set permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
