- name: Disable mysql current version
  ansible.builtin.command: yum module disable mysql -y 

- name: copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: set mysql root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1